controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /
    controller: App\Controller\HomeController::index
login:
    path: /connexion
    controller: App\Controller\LoginController::index
etud:
    path: /etudiants
    controller: App\Controller\EtudiantsController::index
